SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES = $(PWD)/../../rtl/mmu_pkg.sv $(PWD)/../../rtl/permission_checker.sv
TOPLEVEL = permission_checker
MODULE = test_permission_checker
COMPILE_ARGS = -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim
