SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES = $(PWD)/../../rtl/mmu_pkg.sv $(PWD)/../../rtl/page_table_walker.sv
TOPLEVEL = page_table_walker
MODULE = test_page_table_walker
COMPILE_ARGS = -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim
